[project]
name = "laboratorio-ia"
package-mode = false
version = "0.1.0"
description = ""
authors = [
    {name = "cristophermalagaespinoza",email = "cristophermalagaespinoza@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python (>=4.13.0.92,<5.0.0.0)",
    "numpy (>=2.4.4,<3.0.0)",
    "matplotlib (>=3.10.9,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]
[tool.poetry]
# ... otros ajustes ...
packages = [{include = "image_processing", from = "src"}]
